# Generated by Django 5.2.8 on 2025-12-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contas',
            new_name='Conta',
        ),
    ]
